environment:
  nodejs_version: "16"
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: iby7eGIq6RR1VbKpEvPV5LT1swIlG5/Twp1dexjD1iQUdTjUKwMFhYS4Nute/DkY

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off
after_test:
  - node ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info