environment:
  nodejs_version: "16"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off
after_test:
  # - cat ./coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js
  - node ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info
cache:
  - '%APPDATA%\npm-cache'