environment:
  nodejs_version: "16"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
build: off
after_test:
  - cat ./coverage/lcov.info | coveralls
cache:
  - '%APPDATA%\npm-cache'